### ISSUE TITLE
Where are the download and upload buttons?

### ISSUE THREAD

**Issue by Ender-GltHub** [LankyBox01/Customized#26]
I don't get it.

**Comment by LankyBox01** [comment]
wdym? can you supply a screenshot please? They are clearly visible next to the settings button.

**Comment by CST1229** [comment]
![kép](https://user-images.githubusercontent.com/68464103/130360873-15f6f25c-3631-48b5-8fd2-886fc759145a.png)

**Comment by LankyBox01** [comment]
The hell? Where did the file go?

**Comment by LankyBox01** [comment]
Let me restore it from my archives.

**Comment by LankyBox01** [comment]
Thank you for telling me.
